services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - ollama
    environment:
      - NODE_ENV=production

  ollama:
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama-models:/root/.ollama
    command: serve

volumes:
  ollama-models:
