services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs-app
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - ollama
    environment:
      - NODE_ENV=production

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama-models:/root/.ollama

volumes:
  ollama-models:
